- key: tron-testnet
  name: Tron Testnet
  client: tron
  server: https://api.nileex.io/
  height: 4621701
  min_confirmations: 1
  explorer:
    address: https://nile.tronscan.org/#/address/#{address}
    transaction: https://nile.tronscan.org/#/transaction/#{txid}
  status: active
